### ISSUE TITLE
high CPU consuming during the import

### ISSUE THREAD

**Issue by dev590t** [rocky/python3-trepan#40]
trepan3k is very very slow during the import. My CPU increase until 100%.
## Reproduce the issue
```
$ cat testTrepan3k.py 
#!/usr/bin/env python3

import pandas as pd

$ trepan3k testTrepan3k.py 
(/mnt/recoverData/linuxProgram/workspace/Finrl_python3.9/testTrepan3k.py:3): <module>
-> 3 import pandas as pd
(trepan3k) next # this command increase the CPU until 100%
(/mnt/recoverData/linuxProgram/workspace/Finrl_python3.9/testTrepan3k.py:3 @10): <module>
<- 3 import pandas as pd
R=> None
(trepan3k) 
```
## Additional information
I don't have this CPU issue when I execute `import os`.
The difference between `os` and `pandas` is their installation location.
```
$ python3
Python 3.9.9 (main, Jan  1 1970, 00:00:01) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> pandas
<module 'pandas' from '/mnt/recoverData/linuxProgram/workspace/__pypackages__/3.9/lib/pandas/__init__.py'>
>>> import os
>>> os
<module 'os' from '/gnu/store/sz7lkmic6qrhfblrhaqaw0fgc4s9n5s3-python-3.9.9/lib/python3.9/os.py'>
```

Another point, I have install trepan3k with `pip install --user trepan3k`, without using root. Unlike in https://python3-trepan.readthedocs.io/en/latest/install.html. I don't know if that can cause a CPU issue.

**Comment by rocky** [comment]
It is not import per se, but how "next" works. It tries to be more accurate about nexting and that considerably slows things down.
One workaround here is inside trepan3k do an `import pandas` and you'll probably see that things are instantaneous.

The reason you don't see this in os, probably because os has already been imported inside trepan3k while pandas hasn't been.

If I ever get around to rewriting this, that is definitely one of the places where I'll try do something more like what pdb does. 

Setting a breakpoint and running "continue" is faster, but not as fast as pdb or as fast as running that "import" command beforehand. 

But this isn't the way I generally use this because whether you use trepan or pdb the response either way is going to be very slow. Instead I put

```
from trepan.api import debug; debug()
```

before the location I want to stop. And all of the folks I know who use pdb do the corresponding thing there for the same reason. 

By doing there is no slowdown whatsoever until the first breakpoint is hit. 

Something I notice in the session above is that you are using Python 3.9. There currently is no useable decompiler for Python 3.9 let alone one that relates bytecode offsets to source-code fragments. In short, the "deparse" command doesn't work on 3.9.


As for the install instructions, since you are a literary type who may write a blog, feel free to put in a PR to correct the instructions. The source for this doc is at https://github.com/rocky/python3-trepan/blob/master/docs/install.rst

Thanks in advance.

Also while on the topic of blogs, please send me a link to one of your prior blogs so I am as you put it, "convinced". 

Finally, it helps to keep issues to one problem per issue so that we can track things separately.

**Comment by dev590t** [comment]
> Also while on the topic of blogs, please send me a link to one of your prior blogs so I am, as you put it, "convinced".

Haha, I can send you a copy when I will finish writing it, if you want. That could be nice to have the author to review it before I post.

**Comment by rocky** [comment]
The information about about the "next" workaround should be added to the doc somewhere too.
